# Generated by Django 4.0.4 on 2022-05-28 00:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Celdas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=3, unique=True, verbose_name='Celda')),
                ('estado', models.BooleanField(verbose_name='¿Está disponible?')),
            ],
            options={
                'verbose_name': 'Celda',
                'verbose_name_plural': 'Celdas',
                'db_table': 'Celdas',
            },
        ),
        migrations.CreateModel(
            name='Tarifas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.FloatField(verbose_name='Tarifa')),
                ('fecha', models.DateField(auto_now=True, verbose_name='Fecha')),
            ],
            options={
                'verbose_name': 'Tarifa',
                'verbose_name_plural': 'Tarifas',
            },
        ),
        migrations.CreateModel(
            name='Vehiculos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=6, verbose_name='Placa')),
                ('fecha_ingreso', models.DateTimeField(verbose_name='Fecha de ingreso')),
                ('fecha_salida', models.DateTimeField(default=datetime.datetime(2020, 1, 1, 0, 0), verbose_name='Fecha de salida')),
                ('valor_total', models.FloatField(blank=True, null=True, verbose_name='Precio Total')),
                ('celda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_Celda', to='main.celdas', verbose_name='Celda')),
            ],
            options={
                'verbose_name': 'Vehiculo',
                'verbose_name_plural': 'Vehiculos',
                'db_table': 'Vehiculos',
            },
        ),
    ]
