# Generated by Django 4.0.4 on 2022-05-27 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celdas',
            name='estado',
            field=models.BooleanField(verbose_name='¿Está disponible?'),
        ),
        migrations.AlterField(
            model_name='vehiculos',
            name='valor_total',
            field=models.FloatField(null=True, verbose_name='Precio Total'),
        ),
    ]
